//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DermaFram
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicineCRUD
    {
        public int MedicineID { get; set; }
        public string MedicineName { get; set; }
        public string ManufacturingDate { get; set; }
        public string ExpireDate { get; set; }
        public string Quantity { get; set; }
        public string PricePerUnit { get; set; }
    }
}
